checks:
    php: true
build:
    environment:
        php:
            version: 5.6.16
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=phpunit-coverage-clover.xml'
                coverage:
                    file: 'phpunit-coverage-clover.xml'
                    format: 'php-clover'
