checks:
    php: true
build:
    environment:
        php:
            version: 7.3
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=phpunit-coverage-clover'
                coverage:
                    file: 'phpunit-coverage-clover'
                    format: 'php-clover'
