checks:
    php: true
build:
    environment:
        php:
            version: 7.3
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: 'tmp/phpunit-coverage-clover.xml'
                    format: 'php-clover'
